FROM quay.io/pypa/manylinux2010_x86_64
USER root


# Refer to:
# https://github.com/facebook/rocksdb/blob/master/INSTALL.md

RUN yum install -y curl

RUN curl -skL https://github.com/gflags/gflags/archive/refs/tags/v2.0.tar.gz \
        | tar xz -C /tmp/ \
    && cd /tmp/gflags-2.0 \
    && ./configure && make && make install

RUN yum install -y snappy snappy-devel
RUN yum install -y zlib zlib-devel
RUN yum install -y bzip2 bzip2-devel
RUN yum install -y lz4-devel

RUN curl -skL https://github.com/facebook/zstd/archive/v1.3.8.tar.gz \
        | tar xz -C /tmp/ \
    && cd /tmp/zstd-1.3.8 \
    && make && make install

ARG ROCKSDB_VERSION=6.17.3

RUN curl -skL https://github.com/facebook/rocksdb/archive/refs/tags/v${ROCKSDB_VERSION}.tar.gz \
        | tar xz -C /tmp/ \
    && cd /tmp/rocksdb-${ROCKSDB_VERSION} \
    && PORTABLE=1 DISABLE_WARNING_AS_ERROR=1 make shared_lib \
    && make install-shared \
    && ldconfig

COPY . /src/


ENV PYTHONVERSIONS="cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39"

RUN ( \
        pyvers=( $PYTHONVERSIONS ); \
        for pyver in "${pyvers[@]}"; do \
            pybin=/opt/python/${pyver}/bin; \
            ${pybin}/pip install -e /src/ && ${pybin}/pip uninstall -y bigdict; \
            ${pybin}/pip install -r /src/requirements-test.txt; \
            ${pybin}/pip install build; \
        done \
    )

