#!/bin/bash

set -e

PROJ=bigdict

docker build \
    -f Dockerfile-release \
    --build-arg PROJ=bigdict \
    -t ${PROJ}-release:latest \
    .

docker create --name ${PROJ}-release ${PROJ}-release:latest
rm -rf $(pwd)/build
docker cp ${PROJ}-release:/build build
docker rm -f ${PROJ}-release
