#!/bin/bash

set -e

PROJ=bigdict


docker build \
    -f Dockerfile-release \
    -t ${PROJ}-release:latest \
    .

rm -rf $(pwd)/build
mkdir -p $(pwd)/build

docker run \
    --rm \
    -e HOSTUSER=$(id -u):$(id -g) \
    -v $(pwd)/build:/build \
    ${PROJ}-release:latest \
    bash /src/build-wheels.sh

