#!/bin/bash

# exit on error
set -e

apt-get update
apt-get install --no-install-recommends --no-upgrade -y gcc g++ python3-dev
apt-get install --no-install-recommends --no-upgrade -y \
    libgflags-dev \
    zlib1g-dev \
    libbz2-dev \
    liblz4-dev \
    libzstd-dev \
    libsnappy-dev \
    librocksdb-dev
python -m pip install --no-cache-dir python-rocksdb
apt-get purge -y --auto-remove gcc g++
apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*



